### ISSUE TITLE
Error when calling rdedfann(): read_edf() got an unexpected keyword argument 'delete_file'

### ISSUE THREAD

**Issue by prohor33** [MIT-LCP/wfdb-python#409]
wfdb: 4.0.0

When calling on edf file:
```
from wfdb.io.convert.edf import rdedfann
rdedfann(f"data/{folder}/{filename}")
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [6], in <cell line: 2>()
      1 from wfdb.io.convert.edf import rdedfann
----> 2 rdedfann(f"data/{folder}/{filename}")

File ~/.venv/fecg/lib/python3.8/site-packages/wfdb/io/convert/edf.py:1096, in rdedfann(record_name, pn_dir, delete_file, info_only, record_only, verbose)
   1087     raise Exception(
   1088         "Both `info_only` and `record_only` are set. Only one "
   1089         "can be set at a time."
   1090     )
   1092 # According to the EDF+ docs:
   1093 #   "The coding is EDF compatible in the sense that old EDF software would
   1094 #    simply treat this 'EDF Annotations' signal as if it were a (strange-
   1095 #    looking) ordinary signal"
-> 1096 rec = read_edf(
   1097     record_name,
   1098     pn_dir=pn_dir,
   1099     delete_file=delete_file,
   1100     record_only=True,
   1101     rdedfann_flag=True,
   1102 )
   1104 # Convert from array of integers to ASCII strings
   1105 annotation_string = ""

TypeError: read_edf() got an unexpected keyword argument 'delete_file'
```

**Comment by lai-nick** [comment]
You can Comment it out like this, it will run!!!
![image](https://github.com/MIT-LCP/wfdb-python/assets/60662175/e32755c8-23c4-4be5-9ba8-9afc6b3f5e68)

**Comment by evismoit** [comment]
i believe it has been fixed/removed in version 4.1.2
```
def read_edf(
    record_name,
    pn_dir=None,
    header_only=False,
    verbose=False,
    rdedfann_flag=False,
    encoding="iso8859-1",
):
```

**Comment by ZhijiangTang** [comment]
I have the same problem. The analysis above is correct, but the bug is still not fixed after wfdb is updated to 4.1.2.
